---

- block:

  - name: Downloading binaries
    get_url:
        url: 'https://nodejs.org/dist/{{nodejs_version}}/node-{{nodejs_version}}-linux-x64.tar.xz'
        dest: /root
        mode: 'ug+rw'

  - name: Extracting tar file
    unarchive:
        src: /root/node-{{nodejs_version}}-linux-x64.tar.xz
        dest: /usr/local/bin
        remote_src: True
    #shell: 'tar --strip-components 1 -xf /root/node-{{nodejs_version}}-linux-x64.tar.xz -C /usr/local'

  - name: Installing nodejs
    file:
        src: '/usr/local/bin/node-{{nodejs_version}}-linux-x64/bin/node'
        dest: /usr/local/bin/node
        state: link
        owner: root
        group: root
        mode: 'ug+rwx,a+x'

  - name: Installing npm
    file:
        src: '/usr/local/bin/node-{{nodejs_version}}-linux-x64/bin/npm'
        dest: /usr/local/bin/npm
        state: link
        owner: root
        group: root
        mode: 'ug+rwx,a+x'