---

- block:

  - name: Install supervisord packages
    apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
    with_items:
      - supervisor
      - python-pip

  - name: Enable supervisord on boot
    service: name=supervisor state=started enabled=yes